matrix:
  include:
    - language: generic
      os: osx
      before_install:
        - brew update
        - brew upgrade python
        - virtualenv env -p python
        - source env/bin/activate

language: python

os:
  - linux

python:
  - "3.4"
  - "3.5"
  - "3.6"
  
install:
  - pip install coveralls pytest-cov

script:
  - py.test --cov=py3iperf3
  - coveralls
